### ISSUE TITLE
getting Uncaught TypeError: Cannot assign to read only property 'ReadStream' of object '[object Object]'

### ISSUE THREAD

**Issue by pdeva** [knex/documentation#525]
Seeing this error in console when using Knex.js in a react app with Remix.js.
<img width="1496" alt="Screenshot 2023-06-27 at 1 46 47 PM" src="https://github.com/knex/documentation/assets/3190176/af885dde-45e1-485a-9187-18d36392cf2e">

```
node-modules-polyfills-commonjs:tty:6 Uncaught TypeError: Cannot assign to read only property 'ReadStream' of object '[object Object]'
    at node-modules-polyfills-commonjs:tty (node-modules-polyfills-commonjs:tty:6:25)
    at __require (chunk-FCC3XGIV.js:11:50)
    at node_modules/knex/node_modules/colorette/index.cjs (index.cjs:5:11)
    at __require (chunk-FCC3XGIV.js:11:50)
    at node_modules/knex/lib/logger.js (logger.js:1:15)
    at __require (chunk-FCC3XGIV.js:11:50)
    at node_modules/knex/lib/client.js (client.js:29:16)
    at __require (chunk-FCC3XGIV.js:11:50)
    at node_modules/knex/lib/knex-builder/Knex.js (Knex.js:1:16)
    at __require (chunk-FCC3XGIV.js:11:50)
```

**Comment by rluvaton** [comment]
The website repo has been moved inside the https://github.com/knex/knex repo. Please open a PR there instead: (the website will be under the `docs` folder)
